blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/nakanakaii/otp-service/discussions
    about: Ask questions and share ideas in the community forum.
  - name: Documentation
    url: https://github.com/nakanakaii/otp-service/blob/main/README.md
    about: Read the documentation for getting started and usage guides.